"""Response models for the Gemini Web MCP server."""

from typing import Any, Dict, List
from pydantic import BaseModel, Field


class TaskResult(BaseModel):
    """Result of a single task execution."""

    task_index: int = Field(
        ..., description="Index of the task in the original request list"
    )
    description: str = Field(..., description="Original description of the task")
    status: str = Field(
        ..., description="Status of the specific task (e.g., 'completed', 'error')"
    )
    result: str | None = Field(
        None, description="The content/response generated by the agent"
    )
    error: str | None = Field(None, description="Error message if the task failed")
    metadata: Dict[str, Any] | None = Field(
        None,
        description="Additional metadata about execution (timestamp, tool used, etc.)",
    )


class TaskResponse(BaseModel):
    """Response model for task execution."""

    status: str = Field(
        ...,
        description="Overall status of the request ('success', 'partial_success', 'error', 'processing')",
    )
    message: str = Field(..., description="Summary message of the operation details")
    tasks_completed: int = Field(
        ..., description="Count of successfully completed tasks"
    )
    total_tasks: int = Field(..., description="Total number of tasks received")
    results: List[TaskResult] = Field(..., description="Detailed results for each task")
    execution_time: float | None = Field(
        None, description="Total execution time in seconds"
    )
    chat_url: str | None = Field(None, description="URL of the Gemini chat session")
    request_id: str | None = Field(
        None, description="Unique ID for retrieval via Redis"
    )


class StatusResponse(BaseModel):
    """Response model for task status check."""

    status: str = Field(
        ...,
        description="Status of the request ('processing', 'success', 'partial_success', 'error', 'not_found')",
    )
    is_generating: bool = Field(
        False, description="Whether the browser is currently generating a response."
    )
    tasks_completed: int = Field(0, description="Count of successfully completed tasks")
    total_tasks: int = Field(0, description="Total number of tasks in the request")
    results: List[TaskResult] = Field(
        default_factory=list, description="Results for each task, potentially truncated."
    )
    chat_url: str | None = Field(None, description="URL of the Gemini chat session.")
    message: str | None = Field(None, description="Detailed status message.")


class ScreenshotResponse(BaseModel):
    """Response model for screenshot capture."""

    status: str = Field(..., description="Overall status of the operation")
    screenshot_path: str | None = Field(
        None, description="Absolute path to the saved screenshot"
    )
    message: str | None = Field(None, description="Detailed message or error info")


class SessionStatusResponse(BaseModel):
    """Response model for session status check."""

    status: str = Field(..., description="Overall status ('success' or 'error')")
    authenticated: bool = Field(
        False, description="Whether the user is currently logged in"
    )
    page_loaded: bool = Field(
        False, description="Whether the Gemini page is loaded and interactive"
    )
    url: str = Field(..., description="Current browser URL")
    details: str | None = Field(
        None, description="Additional details about the session state"
    )


class ChatItem(BaseModel):
    """Represents a single chat in the history."""

    title: str = Field(..., description="The title of the chat")
    url: str | None = Field(None, description="The URL of the chat session")


class ChatListResponse(BaseModel):
    """Response model for listing chats."""

    status: str = Field(..., description="Overall status of the operation")
    chats: List[ChatItem] = Field(
        default_factory=list, description="List of recent chats"
    )
    message: str | None = Field(None, description="Detailed message or error info")


class GenericResponse(BaseModel):
    """Generic response model for simple operations."""

    status: str = Field(..., description="Overall status ('success' or 'error')")
    message: str | None = Field(None, description="Detailed message or error info")
