import asyncio
import logging
from pathlib import Path
from typing import Any, Dict, List

from fastmcp import FastMCP
from pydantic import BaseModel, Field
from starlette.responses import JSONResponse
import os
import redis.asyncio as redis
import uuid

from mcp_controller.actions import GeminiPageActions
from mcp_controller.session_manager import SessionManager
from orchestrator.state import AgentState, Task

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)

AUTH_STATE_PATH = Path("auth_state.json")

# Initialize FastMCP server with HTTP transport
mcp = FastMCP("Gemini Web Agent")

# Global session manager
session_manager = SessionManager()
redis_client: redis.Redis = None

# Mapping of active request_ids to the session they are running on (for status checks)
active_task_sessions: Dict[str, GeminiPageActions] = {}

async def get_redis() -> redis.Redis:
    """Get or initialize Redis client"""
    global redis_client
    if redis_client is None:
        redis_url = os.getenv("REDIS_URL", "redis://localhost:6379/0")
        redis_client = redis.from_url(redis_url, decode_responses=True)
    return redis_client


class TaskRequest(BaseModel):
    """Request model for task execution."""

    tasks: List[str] = Field(
        ...,
        description="List of task descriptions to execute sequentially. Each task is processed after the previous one completes.",
        examples=[["Summarize the latest AI news", "Draft a LinkedIn post about it"]],
    )
    tool: str | None = Field(
        None,
        description="Optional tool to use for the tasks. Use 'canvas' for content creation/writing, or 'deep_research' for complex multi-step investigations.",
        examples=["canvas", "deep_research"],
    )
    new_chat: bool = Field(
        True,
        description="Whether to start a new chat session. Set to False to continue/monitor an existing session (e.g., waiting for Deep Research to finish).",
    )


class TaskResult(BaseModel):
    """Result of a single task execution."""

    task_index: int = Field(
        ..., description="Index of the task in the original request list"
    )
    description: str = Field(..., description="Original description of the task")
    status: str = Field(
        ..., description="Status of the specific task (e.g., 'completed', 'error')"
    )
    result: str | None = Field(
        None, description="The content/response generated by the agent"
    )
    error: str | None = Field(None, description="Error message if the task failed")
    metadata: Dict[str, Any] | None = Field(
        None,
        description="Additional metadata about execution (timestamp, tool used, etc.)",
    )


class TaskResponse(BaseModel):
    """Response model for task execution."""

    status: str = Field(
        ...,
        description="Overall status of the request ('success', 'partial_success', 'error')",
    )
    message: str = Field(..., description="Summary message of the operation details")
    tasks_completed: int = Field(
        ..., description="Count of successfully completed tasks"
    )
    total_tasks: int = Field(..., description="Total number of tasks received")
    results: List[TaskResult] = Field(..., description="Detailed results for each task")
    execution_time: float | None = Field(
        None, description="Total execution time in seconds"
    )
    chat_url: str | None = Field(None, description="URL of the Gemini chat session")
    request_id: str | None = Field(
        None, description="Unique ID for retrieval via Redis"
    )


class StatusRequest(BaseModel):
    """Request model for checking task status."""

    request_id: str = Field(..., description="The unique ID of the task request to check.")
    offset: int = Field(
        0, description="Character offset for the result text (useful for pagination)."
    )
    max_chars: int = Field(
        100000, description="Maximum number of characters to return in each result."
    )


class StatusResponse(BaseModel):
    """Response model for task status check."""

    status: str = Field(
        ...,
        description="Status of the request ('processing', 'success', 'partial_success', 'error', 'not_found')",
    )
    is_generating: bool = Field(
        False, description="Whether the browser is currently generating a response."
    )
    tasks_completed: int = Field(0, description="Count of successfully completed tasks")
    total_tasks: int = Field(0, description="Total number of tasks in the request")
    results: List[TaskResult] = Field(
        ..., description="Results for each task, potentially truncated."
    )
    chat_url: str | None = Field(None, description="URL of the Gemini chat session.")
    message: str | None = Field(None, description="Detailed status message.")


class ScreenshotResponse(BaseModel):
    """Response model for screenshot capture."""

    status: str = Field(..., description="Overall status of the operation")
    screenshot_path: str | None = Field(None, description="Absolute path to the saved screenshot")
    message: str | None = Field(None, description="Detailed message or error info")


class SessionStatusResponse(BaseModel):
    """Response model for session status check."""

    status: str = Field(..., description="Overall status ('success' or 'error')")
    authenticated: bool = Field(False, description="Whether the user is currently logged in")
    page_loaded: bool = Field(False, description="Whether the Gemini page is loaded and interactive")
    url: str = Field(..., description="Current browser URL")
    details: str | None = Field(None, description="Additional details about the session state")


class ChatItem(BaseModel):
    """Represents a single chat in the history."""

    title: str = Field(..., description="The title of the chat")
    url: str | None = Field(None, description="The URL of the chat session")


class ChatListResponse(BaseModel):
    """Response model for listing chats."""

    status: str = Field(..., description="Overall status of the operation")
    chats: List[ChatItem] = Field(default_factory=list, description="List of recent chats")
    message: str | None = Field(None, description="Detailed message or error info")


class GenericResponse(BaseModel):
    """Generic response model for simple operations."""

    status: str = Field(..., description="Overall status ('success' or 'error')")
    message: str | None = Field(None, description="Detailed message or error info")


async def execute_tasks_workflow(
    task_descriptions: List[str],
    tool: str | None = None,
    new_chat: bool = True,
    request_id: str | None = None,
) -> TaskResponse:
    """Execute a list of tasks using the Gemini agent workflow"""
    global session_manager, active_task_sessions

    # Acquire session
    if new_chat:
        # Use a worker session for parallelizable tasks
        gemini_actions = await session_manager.get_worker_session()
    else:
        # Use main session for stateful continuations
        gemini_actions = await session_manager.get_main_session()

    screenshot_manager = gemini_actions.screenshot_manager

    # Register active session
    if request_id:
        active_task_sessions[request_id] = gemini_actions

    try:
        # Create tasks from descriptions
        tasks = [Task(description=desc, completed=False) for desc in task_descriptions]

        if not request_id:
            request_id = str(uuid.uuid4())
        initial_state: AgentState = {"tasks": tasks, "current_task_index": 0}

        # Initial save to Redis with 'processing' status
        try:
            r = await get_redis()
            initial_response = TaskResponse(
                status="processing",
                message=f"Starting processing of {len(tasks)} tasks.",
                tasks_completed=0,
                total_tasks=len(tasks),
                results=[],
                request_id=request_id,
            )
            await r.setex(
                f"gemini:response:{request_id}", 86400, initial_response.model_dump_json()
            )
            logging.info(f"✅ Task initialized in Redis with ID: {request_id}")
        except Exception as e:
            logging.error(f"❌ Failed to initialize task in Redis: {e}")

        # Execute workflow
        results = []
        current_state = initial_state

        logging.info(f"\nStarting workflow with {len(tasks)} tasks...")
        if tool:
            logging.info(f"Using tool: {tool}")

        # Step -1: Start new chat (with retries built-in)
        if new_chat:
            try:
                await gemini_actions.start_new_chat()
                await asyncio.sleep(2)  # Wait for new chat to load
            except Exception as e:
                logging.error(f"❌ Failed to start new chat after retries: {e}")
                if screenshot_manager:
                    await screenshot_manager.capture_error(
                        gemini_actions.page, "start_new_chat_workflow", e
                    )
                # Continue anyway, might still work

            # Step 0: Ensure Reasoning mode is active (with retries built-in)
            try:
                await gemini_actions.ensure_reasoning_mode()
            except Exception as e:
                logging.error(f"❌ Failed to ensure Reasoning mode after retries: {e}")
                if screenshot_manager:
                    await screenshot_manager.capture_error(
                        gemini_actions.page, "ensure_reasoning_mode_workflow", e
                    )
                # Continue anyway, might still work in current mode

            # Step 1: Select tool if specified (with retries built-in)
            if tool:
                try:
                    await gemini_actions.select_tool(tool)
                except Exception as e:
                    logging.error(f"❌ Failed to select tool '{tool}' after retries: {e}")
                    if screenshot_manager:
                        await screenshot_manager.capture_error(
                            gemini_actions.page, f"select_tool_{tool}_workflow", e
                        )
                    # This is critical, return error
                    return TaskResponse(
                        status="error",
                        message=f"Failed to select tool '{tool}': {str(e)}",
                        tasks_completed=0,
                        total_tasks=len(tasks),
                        results=[
                            TaskResult(
                                task_index=0,
                                description="Tool selection",
                                status="error",
                                error=str(e),
                                metadata={"tool": tool},
                            )
                        ],
                    )
        else:
            logging.info("Continuing existing chat session (new_chat=False)")

        # Step 2: Process first task (send the query)
        if len(tasks) > 0:
            task_index = 0
            task = current_state["tasks"][task_index]

            logging.info(
                f"Processing task {task_index + 1}/{len(tasks)}: {task.description}"
            )

            try:
                skipped_prompt = False

                # Check for ongoing generation if we are continuing a chat
                if not new_chat and await gemini_actions.is_generating():
                    logging.info(
                        "⏳ Generation currently in progress. Waiting for it to complete instead of sending new prompt..."
                    )

                    # Wait for the current generation to finish
                    # Use a very long timeout (30 mins) specifically for Deep Research cases
                    wait_timeout = (
                        1800000 if tool and tool.lower() == "deep_research" else 300000
                    )
                    (
                        success,
                        details,
                    ) = await gemini_actions.validator.validate_generation_complete(
                        timeout=wait_timeout
                    )

                    if success:
                        logging.info("✓ Ongoing generation finished. Retrieving result.")
                        skipped_prompt = True
                    else:
                        logging.warning(
                            f"⚠ Timeout waiting for ongoing generation: {details}"
                        )
                        # If timeout, we might try to proceed or just error out.
                        # For now, let's assume we can try to retrieve what we have or fail gracefully.

                if not skipped_prompt:
                    # Send the prompt normally
                    await gemini_actions.send_prompt(task.description)

                # Step 3: If Deep Research, wait for plan and confirm (with retries built-in)
                # Only do this if we actually sent a prompt OR if we didn't confirm yet
                if tool and tool.lower() == "deep_research" and not skipped_prompt:
                    logging.info("🔍 Deep Research detected - waiting for plan...")
                    try:
                        # Increased timeout for Deep Research plan generation
                        await gemini_actions.wait_for_deep_research_plan()
                        await gemini_actions.confirm_deep_research_plan()
                        logging.info(
                            "✅ Deep Research plan confirmed. Research is now running."
                        )
                    except Exception as dr_error:
                        logging.error(
                            f"❌ Deep Research plan confirmation failed: {dr_error}"
                        )
                        if screenshot_manager:
                            await screenshot_manager.capture_error(
                                gemini_actions.page, "deep_research_plan_workflow", dr_error
                            )
                        # Return error for Deep Research failures
                        return TaskResponse(
                            status="error",
                            message=f"Deep Research plan failed: {str(dr_error)}",
                            tasks_completed=0,
                            total_tasks=len(tasks),
                            results=[
                                TaskResult(
                                    task_index=task_index,
                                    description=task.description,
                                    status="error",
                                    error=str(dr_error),
                                    metadata={"tool": tool, "phase": "deep_research_plan"},
                                )
                            ],
                        )

                # Obtener respuesta - usar un tiempo de espera mucho mayor para Deep Research
                # Si saltamos el prompt, asumimos que estamos esperando un Deep Research largo o similar
                response_timeout = (
                    1800000
                    if (tool and tool.lower() == "deep_research") or skipped_prompt
                    else 240000
                )
                response_text = await gemini_actions.get_last_response(
                    timeout=response_timeout, tool=tool
                )

                task.completed = True
                results.append(
                    TaskResult(
                        task_index=task_index,
                        description=task.description,
                        status="completed",
                        result=response_text,
                        metadata={"tool": tool, "skipped_prompt": skipped_prompt},
                    )
                )
                logging.info(f"✅ TASK COMPLETED: {task.description}\nRESULT:\n{response_text}")

                current_state["tasks"][task_index] = task
                current_state["current_task_index"] += 1

            except Exception as e:
                logging.error(f"Error processing task: {e}")
                results.append(
                    TaskResult(
                        task_index=task_index,
                        description=task.description,
                        status="error",
                        error=str(e),
                        metadata={"tool": tool},
                    )
                )

        logging.info("Workflow completed successfully.")

        completed_count = len([r for r in results if r.status == "completed"])
        overall_status = (
            "success"
            if completed_count == len(tasks)
            else "partial_success"
            if completed_count > 0
            else "error"
        )

        current_url = gemini_actions.page.url if gemini_actions.page else None

        # Save final result to Redis
        try:
            r = await get_redis()
            # Store result for 24 hours
            response_model = TaskResponse(
                status=overall_status,
                message=f"Processed {len(results)} tasks. {completed_count}/{len(tasks)} successful.",
                tasks_completed=completed_count,
                total_tasks=len(tasks),
                results=results,
                chat_url=current_url,
                request_id=request_id,
            )
            await r.setex(
                f"gemini:response:{request_id}", 86400, response_model.model_dump_json()
            )
            logging.info(f"✅ Final response saved to Redis with ID: {request_id}")
        except Exception as e:
            logging.error(f"❌ Failed to save final response to Redis: {e}")

        return TaskResponse(
            status=overall_status,
            message=f"Processed {len(results)} tasks. {completed_count}/{len(tasks)} successful.",
            tasks_completed=completed_count,
            total_tasks=len(tasks),
            results=results,
            chat_url=current_url,
            request_id=request_id,
        )

    finally:
        # Cleanup
        if request_id and request_id in active_task_sessions:
            del active_task_sessions[request_id]
        
        # Release session if it's a worker (new_chat=True)
        # Main session (new_chat=False) is kept active
        if new_chat:
            await session_manager.release_session(gemini_actions)


@mcp.tool()
async def execute_gemini_tasks(
    tasks: List[str], tool: str | None = None, new_chat: bool = True
) -> TaskResponse:
    """
    Execute a list of tasks or queries using the Gemini Web Agent.

    GUIDANCE FOR THE LLM:
    - ALWAYS set `new_chat=True` (default) for new, independent requests.
    - Set `new_chat=False` ONLY when you need to:
        1. Monitor a long-running task like 'deep_research' that was previously started.
        2. Continue a multi-turn conversation where previous context on the same page is required.
    - If a 'deep_research' task returns a status indicating it's still working or waiting for confirmation,
      the NEXT call to this tool to check status MUST use `new_chat=False`.

    Use this tool when you need to:
    - Perform general internet searches or research.
    - Ask questions requiring up-to-date knowledge.
    - Draft content using the Canvas tool (better for writing).
    - Conduct deep investigations using the Deep Research tool.

    Args:
        tasks: List of task descriptions. These are executed in order.
               Example: ["Find the price of BTC", "Calculate 5% of that price"]
        tool: Optional capability to enable.
              - 'canvas': Best for writing blog posts, code, or structured documents.
              - 'deep_research': Best for extensive topics requiring browsing multiple sources and synthesizing a report.
              - None: Uses standard chat mode (good for quick answers and simple logic).
        new_chat: Whether to start a new chat session. Defaults to True.
                  Set to False to continue/monitor an existing session (CRITICAL for Deep Research monitoring).

    Returns:
        TaskResponse object containing:
        - status: "processing" (calls are now asynchronous)
        - request_id: The ID to poll for results with get_gemini_task_status
    """
    try:
        # Generate ID and save initial state
        request_id = str(uuid.uuid4())

        initial_response = TaskResponse(
            status="processing",
            message="Task started in background",
            tasks_completed=0,
            total_tasks=len(tasks),
            results=[],
            request_id=request_id,
        )

        # Save to Redis immediately so polling works
        try:
            r = await get_redis()
            await r.setex(
                f"gemini:response:{request_id}",
                86400,
                initial_response.model_dump_json(),
            )
        except Exception as e:
            logging.error(f"Failed to set initial Redis state: {e}")
            # We continue even if Redis fails, though polling might be flaky

        # Launch background task
        asyncio.create_task(
            execute_tasks_workflow(tasks, tool, new_chat, request_id=request_id)
        )

        return initial_response

    except Exception as e:
        logging.exception("An error occurred in execute_gemini_tasks")
        return TaskResponse(
            status="error",
            message=str(e),
            tasks_completed=0,
            total_tasks=len(tasks),
            results=[],
        )


@mcp.tool()
async def get_gemini_task_status(
    request_id: str, offset: int = 0, max_chars: int = 100000
) -> StatusResponse:
    """
    Retrieve the status or results of a previously started Gemini task.

    GUIDANCE FOR THE LLM:
    - Use this tool when you have a `request_id` and need to:
        1. Monitor a long-running 'deep_research' or Canvas task.
        2. Retrieve a response that was too large to be fully returned (use `offset` and `max_chars`).
        3. Check if a task that timed out has completed in the background.
    - If the status is 'processing', you can call this tool again after a short delay.
    - If a result is truncated, increase the `offset` in subsequent calls to read more.

    Args:
        request_id: The unique ID returned when the task was started.
        offset: Character index to start reading from (for large responses).
        max_chars: Maximum number of characters to return for each task result.

    Returns:
        StatusResponse containing the status, current generation state, and results (potentially truncated).
    """
    return await execute_get_gemini_task_status(request_id, offset, max_chars)


@mcp.tool()
async def refresh_gemini_auth() -> GenericResponse:
    """
    Refreshes the Gemini session authentication by running the remote auth script.

    Use this tool when:
    1. The session has expired or is invalid.
    2. You receive authentication errors.
    3. `get_gemini_session_status` returns authenticated=False.

    This runs `./run_auth_remote.sh` which launches a browser in a virtual display
    to restore the session using the stored credentials and device trust.

    Returns:
        GenericResponse indicating success or failure.
    """
    logging.info("♻️ Refreshing Gemini authentication...")
    
    script_path = Path("./run_auth_remote.sh").resolve()
    if not script_path.exists():
        return GenericResponse(
            status="error", 
            message=f"Auth script not found at {script_path}"
        )

    try:
        # Run the script asynchronously
        process = await asyncio.create_subprocess_exec(
            str(script_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(script_path.parent)
        )

        stdout, stderr = await process.communicate()
        
        stdout_str = stdout.decode().strip()
        stderr_str = stderr.decode().strip()

        if process.returncode == 0:
            logging.info("✅ Auth refresh successful.")
            
            # Reload the browser contexts
            global session_manager
            await session_manager.reload_auth()
            
            return GenericResponse(
                status="success", 
                message=f"Authentication refreshed successfully.\nLogs:\n{stdout_str}"
            )
        else:
            logging.error(f"❌ Auth refresh failed: {stderr_str}")
            return GenericResponse(
                status="error", 
                message=f"Authentication refresh failed (Code {process.returncode}).\nError:\n{stderr_str}\n\nOutput:\n{stdout_str}\n\nIf this persists, please perform manual authentication."
            )

    except Exception as e:
        logging.exception("Error running auth refresh script")
        return GenericResponse(status="error", message=str(e))


@mcp.tool()
async def take_gemini_screenshot(name: str = "manual_capture") -> ScreenshotResponse:
    """
    Capture a screenshot of the current Gemini session (Main session).

    Use this tool when you need visual confirmation of the current UI state,
    especially if you suspect something is wrong or if you want to see a generated
    image, chart, or the Reasoning block.

    Args:
        name: A descriptive name for the screenshot (e.g., 'research_plan_ready')

    Returns:
        ScreenshotResponse containing the status and the absolute path to the image.
    """
    global session_manager
    
    try:
        session = await session_manager.get_main_session()
        path = await session.take_screenshot(name)
        return ScreenshotResponse(status="success", screenshot_path=path, message="Screenshot captured successfully.")
    except Exception as e:
        logging.error(f"Error capturing screenshot: {e}")
        return ScreenshotResponse(status="error", message=str(e))


@mcp.tool()
async def get_gemini_session_status() -> SessionStatusResponse:
    """
    Check if the current browser session is still active and authenticated.

    Use this tool to verify if Gemini is ready to receive prompts or if the session
    has expired (requiring an update to auth_state.json).

    Returns:
        SessionStatusResponse with authentication and page load status.
    """
    global session_manager

    try:
        session = await session_manager.get_main_session()
        status_info = await session.check_session_status()
        return SessionStatusResponse(
            status="success",
            authenticated=status_info["authenticated"],
            page_loaded=status_info["page_loaded"],
            url=status_info["url"],
            details=status_info["details"]
        )
    except Exception as e:
        logging.error(f"Error checking session status: {e}")
        return SessionStatusResponse(
            status="error",
            authenticated=False,
            page_loaded=False,
            url="Error",
            details=str(e)
        )


@mcp.tool()
async def upload_file_to_gemini(file_path: str) -> GenericResponse:
    """
    Upload a local file to the current Gemini session (Main session).

    Use this tool to provide documents, images, or data files for Gemini to analyze.
    After uploading, you can use `execute_gemini_tasks` to ask questions about the file.

    Args:
        file_path: Absolute path to the file to upload.

    Returns:
        GenericResponse indicating success or failure.
    """
    global session_manager
    
    try:
        session = await session_manager.get_main_session()
        await session.upload_file(file_path)
        return GenericResponse(status="success", message=f"File '{os.path.basename(file_path)}' uploaded successfully.")
    except Exception as e:
        logging.error(f"Error uploading file: {e}")
        return GenericResponse(status="error", message=str(e))


@mcp.tool()
async def list_gemini_chats() -> ChatListResponse:
    """
    List recent chat titles from the Gemini history sidebar.

    Use this tool to see available persistent conversations that you can switch to.

    Returns:
        ChatListResponse containing a list of chat titles and URLs.
    """
    global session_manager
    
    try:
        session = await session_manager.get_main_session()
        chats_data = await session.list_chats()
        chats = [ChatItem(title=c["title"], url=c.get("url")) for c in chats_data]
        return ChatListResponse(status="success", chats=chats)
    except Exception as e:
        logging.error(f"Error listing chats: {e}")
        return ChatListResponse(status="error", message=str(e))


@mcp.tool()
async def switch_gemini_chat(chat_title: str) -> GenericResponse:
    """
    Switch the browser context to an existing chat from the history.

    Use this tool to continue a specific conversation by its title.

    Args:
        chat_title: The exact or partial title of the chat to switch to.

    Returns:
        GenericResponse indicating if the switch was successful.
    """
    global session_manager
    
    try:
        session = await session_manager.get_main_session()
        success = await session.switch_chat(chat_title)
        if success:
            return GenericResponse(status="success", message=f"Switched to chat: {chat_title}")
        else:
            return GenericResponse(status="error", message=f"Chat '{chat_title}' not found.")
    except Exception as e:
        logging.error(f"Error switching chat: {e}")
        return GenericResponse(status="error", message=str(e))


async def execute_get_gemini_task_status(
    request_id: str, offset: int = 0, max_chars: int = 100000
) -> StatusResponse:
    """Implementation of get_gemini_task_status for testing and internal use."""
    global active_task_sessions
    
    try:
        r = await get_redis()
        data = await r.get(f"gemini:response:{request_id}")

        if not data:
            return StatusResponse(
                status="not_found",
                message=f"No task found with ID {request_id}",
                results=[],
            )

        task_response = TaskResponse.model_validate_json(data)
        is_gen = False

        # If it's still processing, check the actual browser state if possible
        if task_response.status == "processing":
            # Access the specific session working on this request
            gemini_actions = active_task_sessions.get(request_id)
            if gemini_actions:
                try:
                    is_gen = await gemini_actions.is_generating()
                except Exception:
                    pass

        # Apply offset and max_chars to results
        processed_results = []
        for res in task_response.results:
            new_res = res.model_copy()
            if new_res.result:
                full_text = new_res.result
                text_len = len(full_text)

                if offset < text_len:
                    end = min(offset + max_chars, text_len)
                    new_res.result = full_text[offset:end]

                    # Add metadata about truncation
                    if not new_res.metadata:
                        new_res.metadata = {}
                    new_res.metadata["total_length"] = text_len
                    new_res.metadata["offset"] = offset
                    new_res.metadata["truncated"] = end < text_len
                else:
                    new_res.result = ""
                    if not new_res.metadata:
                        new_res.metadata = {}
                    new_res.metadata["total_length"] = text_len
                    new_res.metadata["offset"] = offset
                    new_res.metadata["error"] = "Offset out of bounds"

            processed_results.append(new_res)

        return StatusResponse(
            status=task_response.status,
            is_generating=is_gen,
            tasks_completed=task_response.tasks_completed,
            total_tasks=task_response.total_tasks,
            results=processed_results,
            chat_url=task_response.chat_url,
            message=task_response.message,
        )

    except Exception as e:
        logging.exception(f"Error checking task status for {request_id}")
        return StatusResponse(status="error", message=str(e), results=[])


@mcp.custom_route("/tasks", methods=["POST"])
async def create_tasks_endpoint(request):
    """
    HTTP endpoint to execute Gemini tasks.

    POST /tasks
    {
        "tasks": ["task 1 description", "task 2 description"],
        "tool": "canvas" | "deep_research" | null,  (optional)
        "new_chat": true | false (optional, defaults to true)
    }
    """
    try:
        # Parse JSON body manually
        import json

        body = await request.body()
        data = json.loads(body)
        tasks = data.get("tasks", [])
        tool = data.get("tool", None)
        new_chat = data.get("new_chat", True)

        response = await execute_tasks_workflow(tasks, tool, new_chat)
        return JSONResponse(response.model_dump())
    except Exception as e:
        logging.exception("An error occurred in the /tasks endpoint")
        return JSONResponse(
            {
                "status": "error",
                "message": str(e),
                "tasks_completed": 0,
                "total_tasks": len(tasks) if "tasks" in locals() else 0,
                "results": [],
            },
            status_code=500,
        )


@mcp.custom_route("/health", methods=["GET"])
async def health_check(request):
    """Health check endpoint"""
    global session_manager
    return JSONResponse(
        {
            "status": "healthy",
            "browser_initialized": session_manager.context is not None,
            "auth_file_exists": AUTH_STATE_PATH.exists(),
        }
    )


if __name__ == "__main__":
    # Note: Browser will be initialized lazily on first request
    # to avoid blocking server startup
    logging.info("Starting MCP server...")
    logging.info("Browser will initialize on first task request")

    # Run the MCP server with HTTP transport
    mcp.run()
