import asyncio
import logging
from pathlib import Path
from typing import List, Dict, Any
from playwright.async_api import async_playwright, BrowserContext, Page, TimeoutError as PlaywrightTimeoutError
from fastmcp import FastMCP
from pydantic import BaseModel, Field
from starlette.responses import JSONResponse

from mcp_controller.actions import GeminiPageActions
from orchestrator.state import AgentState, Task
from orchestrator.graph import create_workflow
from utils.screenshot_manager import ScreenshotManager

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

AUTH_STATE_PATH = Path("auth_state.json")

# Initialize FastMCP server with HTTP transport
mcp = FastMCP("Gemini Web Agent")

# Global browser context (will be initialized on startup)
browser_context: BrowserContext = None
gemini_page: Page = None
gemini_actions: GeminiPageActions = None
screenshot_manager: ScreenshotManager = None


class TaskRequest(BaseModel):
    """Request model for task execution."""
    
    tasks: List[str] = Field(
        ..., 
        description="List of task descriptions to execute sequentially. Each task is processed after the previous one completes.",
        examples=[["Summarize the latest AI news", "Draft a LinkedIn post about it"]]
    )
    tool: str | None = Field(
        None, 
        description="Optional tool to use for the tasks. Use 'canvas' for content creation/writing, or 'deep_research' for complex multi-step investigations.",
        examples=["canvas", "deep_research"]
    )


class TaskResult(BaseModel):
    """Result of a single task execution."""
    
    task_index: int = Field(..., description="Index of the task in the original request list")
    description: str = Field(..., description="Original description of the task")
    status: str = Field(..., description="Status of the specific task (e.g., 'completed', 'error')")
    result: str | None = Field(None, description="The content/response generated by the agent")
    error: str | None = Field(None, description="Error message if the task failed")
    metadata: Dict[str, Any] | None = Field(None, description="Additional metadata about execution (timestamp, tool used, etc.)")


class TaskResponse(BaseModel):
    """Response model for task execution."""
    
    status: str = Field(..., description="Overall status of the request ('success', 'partial_success', 'error')")
    message: str = Field(..., description="Summary message of the operation details")
    tasks_completed: int = Field(..., description="Count of successfully completed tasks")
    total_tasks: int = Field(..., description="Total number of tasks received")
    results: List[TaskResult] = Field(..., description="Detailed results for each task")
    execution_time: float | None = Field(None, description="Total execution time in seconds")
    chat_url: str | None = Field(None, description="URL of the Gemini chat session")


async def setup_browser_context(p) -> tuple[BrowserContext, Page]:
    """Sets up the Playwright browser context and page"""
    if not AUTH_STATE_PATH.exists():
         logging.warning(f"Auth file not found at {AUTH_STATE_PATH}. Attempting to run without auth (might fail).")

    logging.info("Launching browser...")
    # Use standard launch instead of persistent context for better Docker compatibility
    browser = await p.chromium.launch(
        headless=True,
        args=[
            "--disable-blink-features=AutomationControlled",
            "--no-sandbox",
            "--disable-infobars",
            "--disable-dev-shm-usage",
        ],
        ignore_default_args=["--enable-automation"]
    )
    
    # Create context with storage state if available
    context_args = {
        'viewport': {'width': 1920, 'height': 1080},
        'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }
    
    if AUTH_STATE_PATH.exists():
        logging.info(f"Loading auth state from {AUTH_STATE_PATH}")
        context_args['storage_state'] = AUTH_STATE_PATH
        
    context = await browser.new_context(**context_args)
    page = await context.new_page()
    
    # Stealth scripts
    await page.add_init_script("""
        Object.defineProperty(navigator, 'webdriver', {
            get: () => undefined
        });
    """)
    
    # Navigate to Gemini
    logging.info("Navigating to Gemini...")
    try:
        await page.goto("https://gemini.google.com/")
        await page.wait_for_load_state("domcontentloaded", timeout=30000)
    except Exception as e:
        logging.warning(f"Warning: Page load issue: {e}")
    
    return context, page


async def execute_tasks_workflow(task_descriptions: List[str], tool: str | None = None) -> TaskResponse:
    """Execute a list of tasks using the Gemini agent workflow"""
    global gemini_actions, browser_context, gemini_page, screenshot_manager
    
    # Lazy initialization of browser
    if not gemini_actions:
        logging.info("Initializing browser on first request...")
        playwright = await async_playwright().start()
        browser_context, gemini_page = await setup_browser_context(playwright)
        gemini_actions = GeminiPageActions(gemini_page)
        screenshot_manager = ScreenshotManager()
        logging.info("Browser initialized successfully.")

    
    # Create tasks from descriptions
    tasks = [Task(description=desc, completed=False) for desc in task_descriptions]
    
    initial_state: AgentState = {
        "tasks": tasks,
        "current_task_index": 0
    }
    
    # Create workflow
    app = create_workflow(gemini_actions)
    
    # Execute workflow
    results = []
    current_state = initial_state
    
    logging.info(f"\nStarting workflow with {len(tasks)} tasks...")
    if tool:
        logging.info(f"Using tool: {tool}")
    
    # Step -1: Start new chat (with retries built-in)
    try:
        await gemini_actions.start_new_chat()
        await asyncio.sleep(2) # Wait for new chat to load
    except Exception as e:
        logging.error(f"❌ Failed to start new chat after retries: {e}")
        if screenshot_manager:
            await screenshot_manager.capture_error(gemini_page, "start_new_chat_workflow", e)
        # Continue anyway, might still work

    # Step 0: Ensure Reasoning mode is active (with retries built-in)
    try:
        await gemini_actions.ensure_reasoning_mode()
    except Exception as e:
        logging.error(f"❌ Failed to ensure Reasoning mode after retries: {e}")
        if screenshot_manager:
            await screenshot_manager.capture_error(gemini_page, "ensure_reasoning_mode_workflow", e)
        # Continue anyway, might still work in current mode

    
    # Step 1: Select tool if specified (with retries built-in)
    if tool:
        try:
            await gemini_actions.select_tool(tool)
        except Exception as e:
            logging.error(f"❌ Failed to select tool '{tool}' after retries: {e}")
            if screenshot_manager:
                await screenshot_manager.capture_error(gemini_page, f"select_tool_{tool}_workflow", e)
            # This is critical, return error
            return TaskResponse(
                status="error",
                message=f"Failed to select tool '{tool}': {str(e)}",
                tasks_completed=0,
                total_tasks=len(tasks),
                results=[TaskResult(
                    task_index=0,
                    description="Tool selection",
                    status="error",
                    error=str(e),
                    metadata={"tool": tool}
                )]
            )
    
    # Step 2: Process first task (send the query)
    if len(tasks) > 0:
        task_index = 0
        task = current_state["tasks"][task_index]
        
        logging.info(f"Processing task {task_index + 1}/{len(tasks)}: {task.description}")
        
        try:
            # Send the prompt
            await gemini_actions.send_prompt(task.description)
            
            # Step 3: If Deep Research, wait for plan and confirm (with retries built-in)
            if tool and tool.lower() == "deep_research":
                logging.info("🔍 Deep Research detected - waiting for plan...")
                try:
                    # Increased timeout for Deep Research plan generation
                    await gemini_actions.wait_for_deep_research_plan()
                    await gemini_actions.confirm_deep_research_plan()
                    logging.info("✅ Deep Research plan confirmed. Research is now running.")
                except Exception as dr_error:
                    logging.error(f"❌ Deep Research plan confirmation failed: {dr_error}")
                    if screenshot_manager:
                        await screenshot_manager.capture_error(gemini_page, "deep_research_plan_workflow", dr_error)
                    # Return error for Deep Research failures
                    return TaskResponse(
                        status="error",
                        message=f"Deep Research plan failed: {str(dr_error)}",
                        tasks_completed=0,
                        total_tasks=len(tasks),
                        results=[TaskResult(
                            task_index=task_index,
                            description=task.description,
                            status="error",
                            error=str(dr_error),
                            metadata={"tool": tool, "phase": "deep_research_plan"}
                        )]
                    )
            
            # Get response
            response_text = await gemini_actions.get_last_response()
            
            task.completed = True
            results.append(TaskResult(
                task_index=task_index,
                description=task.description,
                status="completed",
                result=response_text,
                metadata={"tool": tool}
            ))
            
            current_state["tasks"][task_index] = task
            current_state["current_task_index"] += 1
            
        except Exception as e:
            logging.error(f"Error processing task: {e}")
            results.append(TaskResult(
                task_index=task_index,
                description=task.description,
                status="error",
                error=str(e),
                metadata={"tool": tool}
            ))
    
    logging.info("Workflow completed successfully.")
    
    completed_count = len([r for r in results if r.status == "completed"])
    overall_status = "success" if completed_count == len(tasks) else "partial_success" if completed_count > 0 else "error"
    
    # Attempt to get a specific chat URL if we are still on the root app URL
    if gemini_page and gemini_page.url.endswith("/app"):
        logging.info("URL is generic, waiting for update...")
        try:
            # Wait up to 5 seconds for URL to change to contain a chat ID
            # Regex match for /app/[a-zA-Z0-9]+
            await gemini_page.wait_for_url(lambda url: len(url.split("/")) > 4, timeout=5000)
        except Exception:
            logging.info("URL did not update to specific chat ID.")

    current_url = gemini_page.url if gemini_page else None
    
    return TaskResponse(
        status=overall_status,
        message=f"Processed {len(results)} tasks. {completed_count}/{len(tasks)} successful.",
        tasks_completed=completed_count,
        total_tasks=len(tasks),
        results=results,
        chat_url=current_url
    )


@mcp.tool()
async def execute_gemini_tasks(tasks: List[str], tool: str | None = None) -> TaskResponse:
    """
    Execute a list of tasks or queries using the Gemini Web Agent.
    
    Use this tool when you need to:
    - Perform general internet searches or research.
    - Ask questions requiring up-to-date knowledge.
    - Draft content using the Canvas tool (better for writing).
    - Conduct deep investigations using the Deep Research tool.
    
    Args:
        tasks: List of task descriptions. These are executed in order. 
               Example: ["Find the price of BTC", "Calculate 5% of that price"]
        tool: Optional capability to enable.
              - 'canvas': Best for writing blog posts, code, or structured documents.
              - 'deep_research': Best for extensive topics requiring browsing multiple sources and synthesizing a report.
              - None: Uses standard chat mode (good for quick answers and simple logic).
        
    Returns:
        TaskResponse object containing:
        - status: Overall success status
        - results: List of individual task results including the text response from Gemini.
    """
    try:
        return await execute_tasks_workflow(tasks, tool)
    except Exception as e:
        logging.exception("An error occurred in execute_gemini_tasks")
        return TaskResponse(
            status="error",
            message=str(e),
            tasks_completed=0,
            total_tasks=len(tasks),
            results=[]
        )


@mcp.custom_route("/tasks", methods=["POST"])
async def create_tasks_endpoint(request):
    """
    HTTP endpoint to execute Gemini tasks.
    
    POST /tasks
    {
        "tasks": ["task 1 description", "task 2 description"],
        "tool": "canvas" | "deep_research" | null  (optional)
    }
    """
    try:
        # Parse JSON body manually
        import json
        body = await request.body()
        data = json.loads(body)
        tasks = data.get("tasks", [])
        tool = data.get("tool", None)
        
        response = await execute_tasks_workflow(tasks, tool)
        return JSONResponse(response.model_dump())
    except Exception as e:
        logging.exception("An error occurred in the /tasks endpoint")
        return JSONResponse({
            "status": "error",
            "message": str(e),
            "tasks_completed": 0,
            "total_tasks": len(tasks) if 'tasks' in locals() else 0,
            "results": []
        }, status_code=500)


@mcp.custom_route("/health", methods=["GET"])
async def health_check(request):
    """Health check endpoint"""
    return JSONResponse({
        "status": "healthy",
        "browser_initialized": gemini_actions is not None,
        "auth_file_exists": AUTH_STATE_PATH.exists()
    })





if __name__ == "__main__":
    # Note: Browser will be initialized lazily on first request
    # to avoid blocking server startup
    logging.info("Starting MCP server...")
    logging.info("Browser will initialize on first task request")
    
    # Run the MCP server with HTTP transport
    mcp.run()
